### ISSUE TITLE
Implementation of DirectIO in other libraries

### ISSUE THREAD

**Issue by mathgcosta** [mmarchetti/DirectIO#11]
I really like to use this DirectIO lib.
What I'm try to do is implement it in other libraries, like <LiquidCrystal.h> for example.
Replace digitalWrite() for Output<>. But I got some issues to implement this in cpp.
Anybody already did that? Create an object Class in other Class.

Thanks.

**Comment by mmarchetti** [comment]
Hi @mathgcosta, it should be possible to create DirectIO objects as class members... like this (which I haven't tested):

```
#include <DirectIO.h>

#define CONTROL_PIN 17

class LCD {
  public:
    LCD();
    void DoSomething();
  private:
    Output<CONTROL_PIN> control_pin;
}

LCD::LCD()
{
  // initialization code here
}

void LCD::DoSomething()
{
  this->control_pin = HIGH;
}

```

What problems are you seeing?

**Comment by mathgcosta** [comment]
Thanks @mmarchetti, I try to use this way that you propose and works!
The thing is, the LCD class has a constructor that gets the pins number and puts on the private variables.

LCD.h:
![image](https://user-images.githubusercontent.com/797213/32966954-cfa80542-cbc2-11e7-8204-96e8fce2b41c.png)

LCD.cpp: [constructor]
![image](https://user-images.githubusercontent.com/797213/32967075-6ae43af8-cbc3-11e7-8dbb-ce9d58c41b18.png)


So the CONTROL_PIN cannot be a constant and that I got stuck.
(I put 9 number as example here in my arduino).

**Comment by mmarchetti** [comment]
To use pin numbers that aren't specified at compile time, you can use the `InputPin` and `OutputPin` classes instead. Those classes allow you to pass the pin number as a constructor argument. That isn't as fast as the regular DirectIO `Output` class, but still around 3x the speed of digitalWrite.

If speed is essential, you could also consider using constants instead of constructor parameters in your class. That would reduce the flexibility (your users would have to edit your constants for their application) but give you greater speed. You might also look at using the DirectIO `OutputPort` class for your 8-bit data bus, if you can live with the restriction that the pins must be on a single hardware port.

**Comment by mathgcosta** [comment]
Thank you so much for help.
I'll have to use OutputPort anyway, I like so much that either.

But, how can I use InputPin allowing pass the pin number as argument. I have tried in some ways but its not work.

My main goal is let LiquidCrystal library more fast, so will need flexibility (I'm going to use interruptions time insted of delay() either). But for now I can use directly the pins number, to solve a problem first.

**Comment by mmarchetti** [comment]
You can do something like this:

```
class LCD {
  LCD(u8 pin_number);
  InputPin my_input;
}

LCD::LCD(u8 pin_number) :
  my_input(pin_number)
{
}
```

**Comment by mathgcosta** [comment]
Hmm. So nice! Thanks.

Although I still have some issues with c++, long time that I did not program this language.

The error was:
![3](https://user-images.githubusercontent.com/797213/32973467-ca2f1b0c-cbde-11e7-8157-0c362023330d.PNG)

In header I declare on private:
![1](https://user-images.githubusercontent.com/797213/32973515-085ba45e-cbdf-11e7-96bb-7311d798cab0.PNG)

And in constructor:
![2](https://user-images.githubusercontent.com/797213/32973617-925d63fe-cbdf-11e7-82fb-4bebb80d2ad3.PNG)

**Comment by mmarchetti** [comment]
Place the `rs_pin(rs)` as an initializer - before the opening `{` of the constructor as in my example.

**Comment by mathgcosta** [comment]
hmmm.
Thank you so much.
It works!

**Comment by mmarchetti** [comment]
Glad to help! Stay in touch with any other feedback you have.
