### ISSUE TITLE
OutputLow not implemented

### ISSUE THREAD

**Issue by mathgcosta** [mmarchetti/DirectIO#12]
Hi @mmarchetti,
When I use OutputLow syntax it shows this error message:

error: 'OutputLow' does not name a type

I check on DirecIO.h header and didn't saw any implementation of these.
I tried to implement _OutputLow_ class based on _Output_, and the result was:

**Original** Output:
![image](https://user-images.githubusercontent.com/797213/33342410-25fd35f8-d469-11e7-9f24-dba7ba5d31ed.png)

I don't know if is in the best implementation, but it works.

**Modified** OutputLow:
![image](https://user-images.githubusercontent.com/797213/33346589-67067fba-d477-11e7-95ae-15fef086874b.png)

**Comment by mmarchetti** [comment]
Thank you. Are you able to open a PR with your implementation?

The only change I would suggest is to negate the return value of `read()`, so it would be `! bitRead(...)`.

**Comment by mathgcosta** [comment]
Hmm. Ok.
I can try do a Pull Request, never done before.

Thanks!

**Comment by mmarchetti** [comment]
Give it a try, if it doesn’t work out, paste your code in a comment here and I will merge it.

**Comment by mathgcosta** [comment]
Hi,

So, I tried to do PR in some ways, but nothing happen.
Is it allowed to do that?
Apparently I can't compare the master branch.

![1](https://user-images.githubusercontent.com/797213/33426853-6a14acf2-d5aa-11e7-9b71-ede36ea337ae.PNG)

Other attempts:
1
![2](https://user-images.githubusercontent.com/797213/33426860-6d676c8c-d5aa-11e7-8c07-ce84ee67a867.PNG)

2
![3](https://user-images.githubusercontent.com/797213/33426865-706e8f50-d5aa-11e7-832d-d442cb082abc.PNG)

**Comment by mmarchetti** [comment]
To open a PR, you'd need to fork the repo into your GitHub account, clone your version locally to your machine, make the changes, push to a branch, then open a PR requesting to merge your branch back into my version of the repository. If you haven't done that before, there is a bit of a learning curve.

If you can just paste in the text of your code here, I will create the PR and merge it in.

**Comment by mathgcosta** [comment]
So cool. Got it.

Didn't know I had to fork first.
It's done.

Thanks.

**Comment by mathgcosta** [comment]
nice!
