### ISSUE TITLE
Using PORT_D for one pin

### ISSUE THREAD

**Issue by mathgcosta** [mmarchetti/DirectIO#14]
Hi,

I'm using atmega328P-AU standalone (the same used in arduino nano boards) and I would like to know if its possible declare, for example,

Output<2> my_output;

as 

OutputPort<PORT_D, 2> my_output;

Or, declare a output pin passing the AVR PORT name, rather than look up equivalent Arduino pin, as reference:

![image](https://user-images.githubusercontent.com/797213/34080439-350d4982-e325-11e7-92e7-4f795eeea8a2.png)

Thanks!

**Comment by mmarchetti** [comment]
You can try using an OutputPort; I'd be interested to know whether a 1-bit port ends up generating the same code. Or you could add a new board type with the associated port-pin mapping in ports.h, which would allow you to use the normal Input and Output classes.

**Comment by mathgcosta** [comment]
Wow, 

Great idea. I'll do that.
Thanks a lot.

**Comment by mathgcosta** [comment]
Hey,

I did this implementation but something is going wrong (the led doesn't blinked and there wasn't compilation error)

Here is your original port.h:
![image](https://user-images.githubusercontent.com/797213/34183125-56691ed0-e500-11e7-8118-2cd3ddad282d.png)

And here is what I wrote below:
![image](https://user-images.githubusercontent.com/797213/34183157-7b3d0f28-e500-11e7-8fcd-dde759217827.png)

Can you see some wrong with it?

**Comment by mmarchetti** [comment]
That looks reasonable, provided it matches your board pinout and you have wired the correct pin.

**Comment by mathgcosta** [comment]
Yeah,

But doesn't work any output pin on the board, neither blink led nor something else =/
And all wires are correct. The same code using Arduino pins works, that new implementation don't.

**Comment by mmarchetti** [comment]
Just checking, is ARDUINO_AVR_NANO defined?

**Comment by mathgcosta** [comment]
You mean, when I compile the code? Like here:

![image](https://user-images.githubusercontent.com/797213/34211114-3b1b3f76-e57f-11e7-83a8-d46da15a705b.png)

On ports.h file I just removed 
  defined (ARDUINO_AVR_NANO) || \\
from here
![image](https://user-images.githubusercontent.com/797213/34210985-db6d7c6a-e57e-11e7-9371-58c11d83b68f.png)

and added a new #elif defined (ARDUINO_AVR_NANO) statement, as I posted before.

**Comment by mmarchetti** [comment]
OK, that seems right... just wanted to be sure it was actually defined at compile time so it would use the correct definitions. (you can always verify by putting a `#warning` statement there). And your code is using pin 32 (`Output<32> my_output`)?

**Comment by mathgcosta** [comment]
Hi @mmarchetti. Sorry for delayed answer, I got so stuffs to do last month and so.
I'm not using pin32, why?
I'll do using #warning and check how it goes.

**Comment by mmarchetti** [comment]
@mathgcosta, You mentioned a compile error - would you post it here? It would also be good if you can post a code section where you are using the Input or Output class.

**Comment by mmarchetti** [comment]
Closing this for now, if more details become available we can reopen.
