### ISSUE TITLE
Upgrade to Socket.io 2.*

### ISSUE THREAD

**Issue by thboomsma** [mmarchetti/DirectIO#16]
Hi i really love the approach you have taken on dynamic sockets.
I noticed that it only works with Socket.IO 1.x.
Are you planning to upgrade it beyond version 2.x?
Could you point on hookups wor such an update? 
I could maybe help coding (with my humble knowledge)
regards
Theo

**Comment by mmarchetti** [comment]
Hi Theo, this library doesn't use Socket.IO... perhaps this issue was intended for a different repo?

**Comment by thboomsma** [comment]
Sorry was mistaken!!
